apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cancel-test
  annotations:
    description: 'A very simple wadm file for testing cancelled HTTP requests'
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0
      traits:
        - type: spreadscaler
          properties:
            instances: 2

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.25.0
      traits:
        - type: link
          properties:
            target:
              name: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 0.0.0.0:8080